version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10.3.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Build
          command: npm run build

  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
        git config --global user.email 'glenn@8888.codes'
        git config --global user.name 'Circle CI Deploy'
      - run: npm install
      - run:
          name: Run Deploy
          command: npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
